const data = {
  products: [
    {
      name: 'Call of Duty: Modern Warfare II',
      slug: 'call-of-duty-modern-warfare-2',
      category: 'PS5 Games',
      image: '/images/p01.jpg',
      logo: '/images/l01.png',
      price: 79,
      countInStock: 99,
      brand: 'Activision',
      rating: 4.8,
      numReviews: 489,
      description: "the sequel to 2019's blockbuster Modern Warfare",
    },
    {
      name: 'Elden Ring',
      slug: 'elden-ring',
      category: 'PS5 Games',
      image: '/images/p02.jpg',
      logo: '/images/l01.png',
      price: 89,
      countInStock: 48,
      brand: 'BANDAI & NAMCO',
      rating: 4.6,
      numReviews: 233,
      description: 'Strong fantasy themes and violence',
    },
    {
      name: 'Horizon Forbidden West',
      slug: 'horizon-forbidden-west',
      category: 'PS5 Games',
      image: '/images/p03.jpg',
      logo: '/images/l01.png',
      price: 109,
      countInStock: 20,
      brand: 'Sony',
      rating: 5.0,
      numReviews: 79,
      description: 'Science fiction themes and violence',
    },
    {
      name: 'Hogwarts Legacy',
      slug: 'hogwarts-legacy',
      category: 'PS5 Games',
      image: '/images/p04.jpg',
      logo: '/images/l01.png',
      price: 99,
      countInStock: 46,
      brand: 'WB Games',
      rating: 4.7,
      numReviews: 103,
      description:
        'Open-world action RPG set in the world first introduced in the Harry Potter books',
    },
  ],
};
export default data;
