import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Sean',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Tom',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Call of Duty: Modern Warfare II',
      slug: 'call-of-duty-modern-warfare-2',
      category: 'PS5 Games',
      image: '/images/p01.jpg',
      logo: '/images/l01.png',
      detail01: '/images/p01_02.jpg',
      detail02: '/images/p01_03.jpg',
      detail03: '/images/p01_04.jpg',
      price: 79,
      countInStock: 0,
      brand: 'Activision',
      rating: 4.8,
      numReviews: 19,
      description: "The sequel to 2019's blockbuster Modern Warfare",
    },
    {
      // _id: '2',
      name: 'Elden Ring',
      slug: 'elden-ring',
      category: 'PS5 Games',
      image: '/images/p02.jpg',
      logo: '/images/l01.png',
      detail01: '/images/p02_02.jpg',
      detail02: '/images/p02_03.jpg',
      detail03: '/images/p02_04.jpg',
      price: 89,
      countInStock: 8,
      brand: 'BANDAI & NAMCO',
      rating: 4.6,
      numReviews: 233,
      description: 'Strong fantasy themes and violence',
    },
    {
      // _id: '3',
      name: 'Horizon Forbidden West',
      slug: 'horizon-forbidden-west',
      category: 'PS5 Games',
      image: '/images/p03.jpg',
      logo: '/images/l01.png',
      detail01: '/images/p03_02.jpg',
      detail02: '/images/p03_03.jpg',
      detail03: '/images/p03_04.jpg',
      price: 109,
      countInStock: 20,
      brand: 'Sony',
      rating: 5.0,
      numReviews: 79,
      description: 'Science fiction themes and violence',
    },
    {
      // _id: '4',
      name: 'Hogwarts Legacy',
      slug: 'hogwarts-legacy',
      category: 'PS5 Games',
      image: '/images/p04.jpg',
      logo: '/images/l01.png',
      detail01: '/images/p04_02.jpg',
      detail02: '/images/p04_03.jpg',
      detail03: '/images/p04_04.jpg',
      price: 99,
      countInStock: 46,
      brand: 'WB Games',
      rating: 4.7,
      numReviews: 103,
      description:
        'Open-world action RPG set in the world first introduced in the Harry Potter books',
    },
  ],
};
export default data;
